= HOWTO: start service as docker container

== Cleaning previously started container

[source,shell]
----
docker ps -a
docker kill pocket-square-articles; docker rm pocket-square-articles
----

== Configuration parameters

Following environment variable are available for global service configuration:

INGEST_REQUEST_SIZE - number of records requested from ingest service at once

MONGO_DATABASE_NAME - mongodb database name to use (default is pocketSquare)

MONGO_AUTH_DATABASE_NAME - mongodb database name used for authentication (default is admin)

MONGO_HOST - host of mongodb instance (default is pocket-square-mongo)

MONGO_PORT - port of mongodb instance (default is 27017)

MONGO_USERNAME - username for authentication to mongodb (default is articlesService)

MONGO_PASSWORD - password for authentication to mongodb

ROOT_LOG_LEVEL - logging level for third-party libraries (default is INFO)

POCKET_SQUARE_LOG_LEVEL - logging level for service code (default is INFO)

== Start service

[source,shell]
----
docker pull pocketsquare/pocket-square-articles:$TAG
docker run -dit --name pocket-square-articles --link pocket-square-ingest --link pocket-square-mongo -e MONGO_PASSWORD=MONGO_PASSWORD -v /logs:/logs -p 28103:8080 pocketsquare/pocket-square-articles:$TAG
----
